export { default as Navbar } from "./components/navbar.svelte" 
export { default as Hero } from "./components/hero.svelte" 
export { default as About } from "./components/about.svelte" 
export { default as Contact } from "./components/contact.svelte" 
export { default as Footer } from "./components/footer.svelte" 
