services:
  app:
    build:
      context: ../
      dockerfile: config/Dockerfile
    container_name: yasasvi-site
    restart: always
    working_dir: /app
    volumes:
      - sqlite_dir:/data
    expose:
      - "11000"
    networks:
      - deploy_net

networks:
  deploy_net:
    external: true

volumes:
  ollama_data:
  sqlite_dir:
