services:
  app:
    build:
      context: ../
      dockerfile: config/Dockerfile
    container_name: yasasvi-site
    image: yasasvi-site:latest
    working_dir: /app
    expose:
      - "11000"
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
